/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteRouteImport } from './routes/project/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as ProjectProjectidRouteImport } from './routes/project/$projectid'

const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectProjectidRoute = ProjectProjectidRouteImport.update({
  id: '/$projectid',
  path: '/$projectid',
  getParentRoute: () => ProjectRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project': typeof ProjectRouteRouteWithChildren
  '/project/$projectid': typeof ProjectProjectidRoute
  '/project/': typeof ProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$projectid': typeof ProjectProjectidRoute
  '/project': typeof ProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project': typeof ProjectRouteRouteWithChildren
  '/project/$projectid': typeof ProjectProjectidRoute
  '/project/': typeof ProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/project' | '/project/$projectid' | '/project/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project/$projectid' | '/project'
  id: '__root__' | '/' | '/project' | '/project/$projectid' | '/project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/project/$projectid': {
      id: '/project/$projectid'
      path: '/$projectid'
      fullPath: '/project/$projectid'
      preLoaderRoute: typeof ProjectProjectidRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
  }
}

interface ProjectRouteRouteChildren {
  ProjectProjectidRoute: typeof ProjectProjectidRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectProjectidRoute: ProjectProjectidRoute,
  ProjectIndexRoute: ProjectIndexRoute,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
